# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07\x65xample\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x0c\x41nomalyReply\x12\x11\n\tanomalies\x18\x01 \x03(\t\"W\n\x04\x44\x61ta\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0btemperatura\x18\x02 \x01(\x02\x12\x18\n\x10velocidade_vento\x18\x03 \x01(\x02\x12\x14\n\x0c\x65nergia_prod\x18\x04 \x01(\x02\"(\n\x08\x44\x61taList\x12\x1c\n\x05\x64\x61\x64os\x18\x01 \x03(\x0b\x32\r.example.Data\"e\n\nStatsReply\x12\x19\n\x11media_temperatura\x18\x01 \x01(\x02\x12\x13\n\x0bmedia_vento\x18\x02 \x01(\x02\x12\x15\n\rmedia_energia\x18\x03 \x01(\x02\x12\x10\n\x08\x66orecast\x18\x04 \x01(\t2\xb8\x01\n\tMyService\x12\x36\n\x08SayHello\x12\x15.example.HelloRequest\x1a\x13.example.HelloReply\x12\x36\n\x0c\x43omputeStats\x12\x11.example.DataList\x1a\x13.example.StatsReply\x12;\n\x0f\x44\x65tectAnomalies\x12\x11.example.DataList\x1a\x15.example.AnomalyReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=26
  _globals['_HELLOREQUEST']._serialized_end=54
  _globals['_HELLOREPLY']._serialized_start=56
  _globals['_HELLOREPLY']._serialized_end=85
  _globals['_ANOMALYREPLY']._serialized_start=87
  _globals['_ANOMALYREPLY']._serialized_end=120
  _globals['_DATA']._serialized_start=122
  _globals['_DATA']._serialized_end=209
  _globals['_DATALIST']._serialized_start=211
  _globals['_DATALIST']._serialized_end=251
  _globals['_STATSREPLY']._serialized_start=253
  _globals['_STATSREPLY']._serialized_end=354
  _globals['_MYSERVICE']._serialized_start=357
  _globals['_MYSERVICE']._serialized_end=541
# @@protoc_insertion_point(module_scope)
